# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

PackingList.destroy_all
Activity.destroy_all
Gear.destroy_all

dayhike = Activity.create(name: "Dayhike", description: "Going for long walks, especially in the country or woods is callled hiking! A hike that is short enough to be completed in a single day", image: 'https://i.imgur.com/fvNFyKQ.jpg')
backpack = Activity.create(name: "Backpack", description: "Backpacking is an adventure that blends hiking with backcountry camping. It lets you broaden your horizons beyond the car campground to enjoy a richer, more immersive outdoor experience. A key distinction from day hiking is the size of your pack—your backpack (and you) must carry all of life’s essentials on your back. And you must choose those essentials with care.", image: 'https://imgur.com/w6LQLkp')
backcountry_ski = Activity.create(name: "Backcountry Skiing", description: "Backcountry skiing is skiing in the backcountry on unmarked or unpatrolled areas, and skiers need to be prepared - ski patrol is not coming to help.", image: 'https://imgur.com/9s6evGP')
climbing = Activity.create(name: "Rock Climbing", description: "Rock climbing can be performed on an indoor rock climbing wall or out in nature. With the right mindset and the best climbing equipment, shoes and gear for safe rock climbing, you can be prepared for unparelleled adventure!", image: 'https://www.msrgear.com/blog/wp-content/uploads/2016/09/Alpine_Climbing_P8200343-3.jpg')
yoga = Activity.create(name: "Mountain Yoga", description: "Embrace the Experience. Being outside can intensify the yoga experience in many ways, since nature inspires all the things you try to drive home with students—focusing awareness, breathing deeply, practicing stillness.", image: 'https://mountainyogasandy.com/wp-content/uploads/2018/01/dsc_9776.jpeg')
mtn_biking = Activity.create(name: "Mountain Biking", description: "Mountain biking is a sport of riding bicycles off-road, often over rough terrain, using specially designed mountain bikes. Mountain bikes share similarities with other bikes but incorporate features designed to enhance durability and performance in rough terrain.", image: 'https://imgur.com/qy2CUV9')
hut = Activity.create(name: "Winter Hut Trip", description: "Immerse yourself in the backcountry with the quickest access to breathtaking lines. Hole up in a hut for a few nights with good company and create memories that will last a lifetime!", image: 'https://cdn.allsummitcounty.com/images/content/5827_7088_Breckenridge_Colorado_Hut_Ski_Trip_lg.jpg')

water = Gear.create(name: "Water Filtration System", description: "", category: "Essential", image: "https://images.squarespace-cdn.com/content/v1/5346a846e4b0101b157468cf/1518269300014-HZRVS3XSC984E8XK7MJC/ke17ZwdGBToddI8pDm48kG87Sfbgg29A4BYEDq3OXvgUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcf4OxbJOyh_wHUnyc4kQLQ6SBshRGOku7c30Y_IRDNPta8R2IY5BHMaEj1zOWoDTZ/Top-down+view+of+the+best+backpacking+water+filters+on+the+market+laid+out+on+a+table+for+size+comparison?format=750w", url: "https://www.rei.com/learn/expert-advice/water-treatment-backcountry.html", weight: "2.0")
fire = Gear.create(name: "Fire Starter (matches or lighter)", description: "", category: "Essential",image: "https://cdn.coolofthewild.com/wp-content/uploads/2018/03/DIY-firestarter-kit.jpg", url: "https://www.outsidepursuits.com/best-fire-starter-reviews/", weight: "0.89")
stove = Gear.create(name: "Stove and Fuel", description: "", category: "Essential",image: "https://www.rei.com/dam/c01_5252_how_to_choose_backpacking_stoves_lg.jpg", url: "https://www.cleverhiker.com/best-backpacking-stoves", weight: "10.9")
knife = Gear.create(name: "Knife", description: "", category: "Essential",image: "https://cdn.shopify.com/s/files/1/0880/2184/files/best-knives-and-multi-tools-for-hikers-and-backpackers-2_a9798339-ed7b-43ca-8ecf-034df05bd8aa.jpg?v=1502306674", url: "https://knifegeeky.com/best-hiking-knife/", weight: "2.5")
utensil = Gear.create(name: "Utensil", description: "", category: "Essential",image: "https://outdoorgearlab-mvnab3pwrvp3t0.stackpathdns.com/photos/17/45/296012_26866_L.jpg", url: "https://www.outdoorgearlab.com/topics/camping-and-hiking/best-sporks", weight: "0.6")
vessel = Gear.create(name: "Cup or Bowl", description: "", category: "Essential",image: "https://www.99boulders.com/wp-content/uploads/2018/10/IMG_20181020_090251461_HDR-e1540818304695.jpg", url: "https://www.99boulders.com/best-backpacking-mugs", weight: "4.7")
water_bottle = Gear.create(name: "Water Bottles", description: "", category: "Essential",image: "https://content.backcountry.com/images/items/900/CAS/CAS0448/S2LCL.jpg", url: "https://www.backcountry.com/water-bottles", weight: "0.8")
bladder = Gear.create(name: "Water Bladder", description: "", category: "Essential",image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQU-sVcr6OmLSFVGcA4bzAtY7Pv9QzStU8_Gw&usqp=CAU", url: "https://www.msrgear.com/water-treatment/storage-bags/dromlite-bags/dromlite-bags.html", weight: "4.6")
gps = Gear.create(name: "Maps and/or GPS on phone", description: "", category: "Essential", image: "https://static1.squarespace.com/static/5346a846e4b0101b157468cf/5346ae88e4b098170d05db98/5c8be1c38165f5e77c26a211/1553181866253/IMG_6202.jpg?format=1500w", url: "https://thedyrt.com/magazine/lifestyle/best-navigation-apps-hiking/", weight: "0.0")
soap = Gear.create(name: "Biodegradable Soap", description: "", category: "Essential",image: "https://i1.wp.com/www.powder.com/wp-content/uploads/2020/06/IMG_4838-scaled.jpg?resize=2560%2C1920&ssl=1", url: "https://www.99boulders.com/best-biodegradable-soaps", weight: "0.0")
headlamp = Gear.create(name: "Headlamp",  description: "", category: "Essential",image: "https://www.campingwithcharlie.com/images/black%20diamond%20spot%20headlamp.PNG", url: "https://www.backcountry.com/explore/how-to-choose-a-headlamp", weight: "3.0")
batteries = Gear.create(name: "Extra Batteries", description: "", category: "Essential",image: "https://www.komando.com/wp-content/uploads/2018/12/batteries-970.jpg", url: "https://www.amazon.com/Household-Batteries/b?ie=UTF8&node=15745581", weight: 0.2)
sunglasses = Gear.create(name: "Sunglasses", description: "", category: "Outerwear", image: "https://cdn.shopify.com/s/files/1/0148/9585/products/BLNDRS_FearlessAnna_FullSpeed_Front_960x480.jpg?v=1582850938", url: "https://www.smithoptics.com/", weight: "1.3")
sunscreen = Gear.create(name: "Sunscreen", description: "", category: "Toiletries", image: "https://images-na.ssl-images-amazon.com/images/I/31x8eyPBk3L.jpg", url: "https://www.consumerreports.org/sunscreens/best-sunscreens-of-the-year/", weight: "4.0")
hat = Gear.create(name: "Sun Hat", description: "", category: "Outerwear", image: "https://cdn.shopify.com/s/files/1/0047/9585/9057/products/BoulderFlatironsGreenTruckerFront_544x512.png?v=1574357629", url: "https://www.katherinehomes.com/collections/hats", weight: "2.5")
beanie = Gear.create(name: "Winter Hat", description: "", category: "Outerwear", image: "https://scene7.zumiez.com/is/image/zumiez/pdp_hero/Carhartt-Teller-Heather-Coal-Beanie-_331145.jpg", url: "https://www.carhartt.com/category/carhartt-accessories-knit-hats", weight: "0.0")
toothbrush = Gear.create(name: "Toothbrush / paste", description: "", category: "Toiletries", image: "https://i5.walmartimages.com/asr/28243528-c34e-4ceb-8690-4ad64a384477_1.dc5a3da55780f062793f5aaa58ff33cd.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff", url: "https://www.amazon.com/s?k=toothbrush&ref=nb_sb_noss_2", weight: "0.63")
chapstick = Gear.create(name: "Chapstick", description: "", category: "Toiletries", image: "https://www.kroger.com/product/images/xlarge/front/0030573072551", url: "https://www.amazon.com/stores/ChapStick/ChapStick/page/2D3E2D32-F6F5-4D71-AB20-F481767ADA19", weight: "0.57")
tp = Gear.create(name: "Toilet Paper and Hand Sanitizer", description: "", category: "Toiletries", image: "https://wrcb.images.worldnow.com/images/19266281_G.jpeg", url: "https://www.rootsimple.com/2014/08/toilet-paper-in-the-woods-a-rant-and-some-advice/", weight: "0.0")
wag_bag = Gear.create(name: "Wag Bag", description: "", category: "Toiletries", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRWsfMDv8URq9lPYEPDLpcGWGqsNiRFlvQnrg&usqp=CAU", url: "https://www.youtube.com/watch?v=BpiX07wPKgE", weight: "0.9")
wipes = Gear.create(name: "Wet Wipes or Face Wipes",  description: "", category: "Toiletries", image: "https://ntg-catalog.imgix.net/products/6815429-11.jpg?w=1200&h=1443&sfrm=jpg&fit=crop", url: "https://www.amazon.com/s?k=face+wipes&i=beauty&ref=nb_sb_noss", weight: "1.0")
waterproof_jacket = Gear.create(name: "Waterproof Jacket", description: "", category: "Outerwear", image: "https://exxpozed-image.de/exxpozed-res.cloudinary.com/image/upload/q_auto:eco,w_550,h_550,c_pad,b_white,d_ph.gif,e_sharpen/v20200218204800/catalog/patagonia-w-torrentshell-jacket-17a-pat-83807-tomato-1.jpg", url: "https://www.theadventurejunkies.com/best-rain-jacket-for-hiking/", weight: "9.1")
waterproof_pants = Gear.create(name: "Waterproof Pants",  description: "", category: "Outerwear",image: "https://hikingpeople.com/wp-content/uploads/2018/11/price-of-waterproof-hiking-pants.jpg", url: "https://hikingpeople.com/best-waterproof-hiking-pants/", weight: "9.3")
down_jacket = Gear.create(name: "Insulating Down Jacket",  description: "", category: "Outerwear",image: "https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2019/12/Best-Down-Jackets-Gear-Patrol-Feature.jpg", url: "https://www.gearpatrol.com/outdoors/a518010/best-down-jackets/", weight: "16.0")
down_pants = Gear.create(name: "Insulated Pants", description: "", category: "Outerwear", image: "https://cdn.shopify.com/s/files/1/0140/2791/5318/products/feathered-friends-helios-down-pants-black_1800x1800.jpg?v=1557080488", url: "https://backpackinglight.com/forums/topic/25895/", weight: "14.0")
gloves = Gear.create(name: "Gloves", description: "", category: "Outerwear", image: "https://www.outsideonline.com/sites/default/files/styles/full-page/public/2019/02/21/gloves-review-test_h.jpg?itok=tgH5yT_f", url: "https://www.outsideonline.com/2390572/best-ski-gloves-review", weight: "7.1")
buff = Gear.create(name: "Bandana or Buff",  description: "", category: "Outerwear",image: "https://www.fontanasports.com/info/default/cache/file/CB1831CE-F8BC-1235-62F679C25F5855D8.jpg", url: "https://www.buff.com/world/", weight: "2.0")
shorts = Gear.create(name: "Shorts", description: "", category: "Clothing", image: "https://www.kuhl.com/media/versions/pdp/5048_mutiny_rivershort_deepharbor_front_ps_pdp_photo.jpg", url: "", weight: "5.4")
tshirt = Gear.create(name: "Wool T-shirt", description: "", category: "Clothing", image: "https://www.rei.com/media/product/818977", url: "https://www.backcountry.com/smartwool-merino-150-t-shirt-short-sleeve-mens", weight: "7.5")
long_sleeve = Gear.create(name: "Long-sleeve Shirt", description: "", category: "Clothing", image: "https://content.backcountry.com/images/items/900/BCC/BCC00C9/ARCFAIISL.jpg", url: "https://www.smartwool.com/", weight: "12.1")
fleece = Gear.create(name: "Fleece Mid Layer", description: "", category: "Clothing", image: "https://www.insidehook.com/wp-content/uploads/2020/08/melanzana.jpg?fit=1500%2C1000", url: "https://melanzana.com/product/micro-grid-hoodie/", weight: "0.0")
cotton_shirt = Gear.create(name: "Cotton Sleep Shirt", description: "", category: "Clothing", image: "https://res.cloudinary.com/teepublic/image/private/s--J6ItCAj4--/t_Resized%20Artwork/c_crop,x_10,y_10/c_fit,w_470/c_crop,g_north_west,h_626,w_470,x_0,y_-47/g_north_west,u_upload:v1462829024:production:blanks:a59x1cgomgu5lprfjlmi,x_-395,y_-372/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1516826478/production/designs/2305884_0.jpg", url: "https://www.teepublic.com/t-shirt/2305884-programmer-t-shirt-coding-joke", weight: "8.0")
long_underwear = Gear.create(name: "Long Underwear / Baselayers", description: "", category: "Clothing", image: "https://images.smartwool.com/is/image/SmartWool/SW019243E44-1-p?$WC-FULLIMAGE$", url: "https://www.smartwool.com/shop/womens-base-layers-1/womens-merino-250-base-layer-pattern-bottom-sw019243?variationId=E44", weight: "7.34")
pants = Gear.create(name: "Pants", description: "", category: "Clothing", image: "https://www.kuhl.com/media/versions/pdp/5603_m_renegaderock_lifestyle_pdp_photo.jpg", url: "https://www.outdoorresearch.com/us/mens-ferrosi-pants-269176", weight: "0.0")
underwear = Gear.create(name: "Underwear", description: "", category: "Clothing", image: "https://www.rei.com/media/product/878282", url: "https://www.patagonia.com/product/womens-active-briefs-underwear/32396.html", weight: "4.8")
socks = Gear.create(name: "Socks", description: "", category: "Clothing", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/darn-tough-1541626319.jpg", url: "https://darntough.com/", weight: "5.0")
sleeping_bag = Gear.create(name: "Sleeping Bag", description: "", category: "Gear", image: "https://dk0fkjygbn9vu.cloudfront.net/cache-buster-11598577613/deuter/mediaroom/product-images/sleeping-bags/down-sleeping-bags/image-thumb__2237__pds__product/3712617-3003-AstroPro800-17-d4.webp", url: "https://www.cleverhiker.com/best-sleeping-bags", weight: "0.0")
sleeping_pad = Gear.create(name: "Sleeping Pad", description: "", category: "Gear", image: "https://images.squarespace-cdn.com/content/v1/5346a846e4b0101b157468cf/1521422192160-KG3UVWA16HILOW1O6R69/ke17ZwdGBToddI8pDm48kDrPwNVXYEunyd5GI-T5dTMUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcjnGyVxz4_7fGUBBocNlg5GFIaMd2sRlNBQxXhqLPHNahoHUF39SckYf9CqjRTAfQ/Closeup+of+layered+backpacking+sleeping+pads+for+thickness+and+texture+comparison", url: "https://www.outdoorgearlab.com/topics/camping-and-hiking/best-sleeping-pad", weight: "18.3")
sleep_socks = Gear.create(name: "Sleep Socks (keep them dry!)", description: "", category: "Clothing", image: "https://image.jimcdn.com/app/cms/image/transf/dimension=1820x1280:format=jpg/path/s37749b31373b40ee/image/i56b4712c7f0cd79a/version/1498982548/image.jpg", url: "https://www.amazon.com/Merino-Thermal-Winter-Womens-Hiking/dp/B07Y2FGYL7", weight: "8.0")
tent = Gear.create(name: "Tent",  description: "", category: "Gear", image: "https://i0.wp.com/alliemtaylor.blog/wp-content/uploads/2019/08/IMG_9796.jpeg?resize=1440%2C1800&ssl=1", url: "https://www.nytimes.com/wirecutter/reviews/best-tent-for-family-and-car-camping/", weight: "112.7")
flipflops = Gear.create(name: "Flipflops", description: "", category: "Footwear", image: "https://images-na.ssl-images-amazon.com/images/I/61csdqpS5sL._AC_UL1280_.jpg", url: "https://www.teva.com/women-flip-flops/", weight: "15.0")
hiking_shoes = Gear.create(name: "Hiking Shoes", description: "", category: "Footwear", image: "https://www.rei.com/media/23fdf0c8-8cd4-47e4-994c-7dba806c87f0?size=646x485", url: "https://www.cleverhiker.com/best-hiking-shoes-men", weight: "26.8")

climbing_shoes = Gear.create(name: "Climbing Shoes", description: "", category: "Footwear", image: "https://cdn8.dissolve.com/p/D1301_119_246/D1301_119_246_1200.jpg", url: "https://www.outdoorgearlab.com/topics/climbing/best-climbing-shoes", weight: "0.0")
rope = Gear.create(name: "Climbing Rope", description: "", category: "Gear", image: "https://d1vs4ggwgd7mlq.cloudfront.net/wp-content/uploads/2017/09/Climbing-Rope-Gavin-Young-iStock-145244284-web.jpg", url: "https://sterlingrope.com/", weight: "0.0")
harness = Gear.create(name: "Harness", description: "", category: "Gear", image: "https://www.roadaffair.com/wp-content/uploads/2019/04/climbing-harness-shutterstock_290476916.jpg", url: "https://www.outdoorgearlab.com/topics/climbing/best-climbing-harness", weight: "0.0")
belay_device = Gear.create(name: "Belay Device", description: "", category: "Gear", image: "", url: "", weight: "0.0")
belay_gloves = Gear.create(name: "Belay Gloves", description: "", category: "Gear", image: "", url: "", weight: "0.0")
helmet_climbing = Gear.create(name: "Climbing Helmet", description: "", category: "Gear", image: "", url: "", weight: "0.0")
helmet_bike = Gear.create(name: "Mountain Biking Helmet", description: "", category: "Gear", image: "", url: "", weight: "0.0")
bike_shoes = Gear.create(name: "Mountain Bike Shoes", description: "", category: "Footwear", image: "", url: "", weight: "0.0")
chamois = Gear.create(name: "Bike Chamois", description: "", category: "Clothing", image: "https://cdn.shopify.com/s/files/1/0178/0546/products/Montcham-ScubaBlue850x1200_1200x.jpg?v=1595433831", url: "https://www.clubrideapparel.com/collections/women-bike-shorts-chamois", weight: "0.0")
padding = Gear.create(name: "Elbow and Knee Pads", description: "", category: "Clothing", image: "", url: "", weight: "0.0")
book = Gear.create(name: "Book or Journal", description: "", category: "Optional", image: "", url: "", weight: "0.0")
compass = Gear.create(name: "Compass", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
daypack = Gear.create(name: "Day Pack", description: "", category: "Gear", image: "", url: "", weight: "0.0")
traditional_backpack = Gear.create(name: "Backpack", description: "", category: "Gear", image: "", url: "", weight: "0.0")
lightweight_backpack = Gear.create(name: "Lightweight Backpack", description: "", category: "Gear", image: "", url: "", weight: "1.5")
hammock = Gear.create(name: "Hammock", description: "", category: "Optional", image: "", url: "", weight: "0.0")
speaker = Gear.create(name: "Bluetooth Speaker", description: "", category: "Optional", image: "", url: "", weight: "0.0")
hiking_poles = Gear.create(name: "Hiking Poles", description: "", category: "Gear", image: "", url: "", weight: "0.0")
first_aid_mini = Gear.create(name: "Mini First Aid Kit", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
first_aid_robust = Gear.create(name: "Robust First Aid Kit", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
cash = Gear.create(name: "Emergency Cash", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
satellite_device = Gear.create(name: "Spot or InReach", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
pcord = Gear.create(name: "Parachute Cord", description: "", category: "Emergency", image: "", url: "", weight: "0.0")
skis = Gear.create(name: "AT Skis", description: "", category: "Gear", image: "https://www.switchbacktravel.com/sites/default/files/articles%20/Backcountry%20ski%20boots%20(m)_0.jpg", url: "https://www.outdoorgearlab.com/topics/snow-sports/best-backcountry-skis", weight: "0.0")
ski_boots = Gear.create(name: "Ski Boots", description: "", category: "Gear", image: "https://i.pinimg.com/originals/fb/08/85/fb088562c4f7e42cc8e8133c9c27bf6e.jpg", url: "https://www.outdoorgearlab.com/topics/snow-sports/best-backcountry-ski-boots", weight: "0.0")
skins = Gear.create(name: "Skins", description: "", category: "Gear", image: "https://images-na.ssl-images-amazon.com/images/I/61dbRnaVQ7L._AC_SL1024_.jpg", url: "https://www.blackdiamondequipment.com/en_US/search?cgid=skins", weight: "0.0")
beacon = Gear.create(name: "Beacon", description: "", category: "Gear", image: "https://www.rei.com/media/7336c3cd-6ff7-4175-93df-715cb8f243ce?size=784x588", url: "https://backcountryaccess.com/en-us/c/rescue-gear/avalanche-beacons/", weight: "0.0")
probe = Gear.create(name: "Probe", description: "", category: "Gear", image: "https://images-na.ssl-images-amazon.com/images/I/51b4AXupDML._AC_SL1000_.jpg", url: "https://backcountryaccess.com/en-us/c/rescue-gear/avalanche-probes/", weight: "0.0")
shovel = Gear.create(name: "Shovel", description: "", category: "Gear", image: "https://mk0theadventuregfnyq.kinstacdn.com/wp-content/uploads/BestAvalancheShovel3.jpg", url: "https://backcountryaccess.com/en-us/c/rescue-gear/avalanche-shovels/", weight: "0.0")
ski_poles = Gear.create(name: "Ski Poles", description: "", category: "Gear", image: "https://i.etsystatic.com/19913857/r/il/ffca26/2239948951/il_794xN.2239948951_2jcn.jpg", url: "https://www.etsy.com/shop/GnarStix", weight: "0.0")
earplugs = Gear.create(name: "Earplugs", description: "", category: "Optional", image: "https://dks.scene7.com/is/image/dkscdn/18FNSUFSFMRPLG50CTGS_is?wid=1080&fmt=jpg", url: "", weight: "0.0")
trash_bag = Gear.create(name: "Extra Trash Bag", description: "", category: "Optional", image: "https://media.istockphoto.com/photos/wrinkled-empty-trash-bag-isolated-on-white-background-used-black-picture-id987276396?k=6&m=987276396&s=170667a&w=0&h=hAj8NhhQNeCDs1dGakc92LDxhV-lGemXIheOUHjlx_Q=", url: "", weight: "0.0")
usb_charger = Gear.create(name: "Portable USB Charger", description: "", category: "Optional", image: "https://webobjects2.cdw.com/is/image/CDW/3831157?$product-main$", url: "", weight: "0.0")
phone_charger = Gear.create(name: "Phone Charger", description: "", category: "Optional", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/directly-above-shot-of-smart-phone-and-charger-royalty-free-image-1135742187-1565730404.jpg?resize=480:*", url: "", weight: "0.0")
gopro = Gear.create(name: "GoPro", description: "", category: "Optional", image: "https://media.dcrainmaker.com/images/2019/10/DSC_7443.jpg", url: "https://gopro.com/en/us/", weight: "3.5")
snacks = Gear.create(name: "Snacks", description: "", category: "Food", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTMYr8dR0iFLzrxFnbNXjkFzfNHur7bXz21Eg&usqp=CAU", url: "https://www.healthline.com/nutrition/backpacking-food", weight: "0.0")
breakfast = Gear.create(name: "Breakfasts", description: "", category: "Food", image: "https://i.pinimg.com/originals/af/e5/3b/afe53bbd5e6cfc5d2d62ae916be47de9.jpg", url: "https://www.backpacker.com/skills/cooking/recipes/breakfast-recipes", weight: "0.0")
lunch = Gear.create(name: "Lunches", description: "", category: "Food", image: "https://www.rei.com/dam/content_09122016_0068_backpacking_meals.jpg", url: "https://www.backcountrycow.com/blog/my-favorite-backpacking-meals", weight: "0.0")
dinner = Gear.create(name: "Dinner", description: "", category: "Food", image: "https://www.backpacker.com/.image/ar_8:10%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTY1MzgzMTIzOTAxNjIxNzg1/trailchef_pb_ramen_05.jpg", url: "https://www.trail.recipes/recipe-collection/main-course/", weight: "0.0")
yoga_mat = Gear.create(name: "Yoga Mat", description: "", category: "Gear", image: "https://media.istockphoto.com/photos/yoga-mats-in-a-garden-picture-id477470416?k=6&m=477470416&s=612x612&w=0&h=zB7oxpAlNiHcGSpN1al_kt9q8MV2atWhSJk3cmCjt7E=", url: "https://society6.com/yoga-mat", weight: "0.0")


# BACKPACK LIST SEEDS
PackingList.create(activity: backpack, gear: water)
PackingList.create(activity: backpack, gear: water_bottle)
PackingList.create(activity: backpack, gear: bladder)
PackingList.create(activity: backpack, gear: fire)
PackingList.create(activity: backpack, gear: stove)
PackingList.create(activity: backpack, gear: knife)
PackingList.create(activity: backpack, gear: utensil)
PackingList.create(activity: backpack, gear: vessel)
PackingList.create(activity: backpack, gear: soap)
PackingList.create(activity: backpack, gear: headlamp)
PackingList.create(activity: backpack, gear: batteries)
PackingList.create(activity: backpack, gear: sunglasses)
PackingList.create(activity: backpack, gear: sunscreen)
PackingList.create(activity: backpack, gear: hat)
PackingList.create(activity: backpack, gear: beanie)
PackingList.create(activity: backpack, gear: toothbrush)
PackingList.create(activity: backpack, gear: chapstick)
PackingList.create(activity: backpack, gear: tp)
PackingList.create(activity: backpack, gear: wipes)
PackingList.create(activity: backpack, gear: waterproof_jacket)
PackingList.create(activity: backpack, gear: waterproof_pants)
PackingList.create(activity: backpack, gear: down_jacket)
PackingList.create(activity: backpack, gear: down_pants)
PackingList.create(activity: backpack, gear: gloves)
PackingList.create(activity: backpack, gear: buff)
PackingList.create(activity: backpack, gear: underwear)
PackingList.create(activity: backpack, gear: socks)
PackingList.create(activity: backpack, gear: long_underwear)
PackingList.create(activity: backpack, gear: shorts)
PackingList.create(activity: backpack, gear: pants)
PackingList.create(activity: backpack, gear: tshirt)
PackingList.create(activity: backpack, gear: long_sleeve)
PackingList.create(activity: backpack, gear: fleece)
PackingList.create(activity: backpack, gear: cotton_shirt)
PackingList.create(activity: backpack, gear: sleeping_bag)
PackingList.create(activity: backpack, gear: sleeping_pad)
PackingList.create(activity: backpack, gear: sleep_socks)
PackingList.create(activity: backpack, gear: tent)
PackingList.create(activity: backpack, gear: flipflops)
PackingList.create(activity: backpack, gear: hiking_shoes)
PackingList.create(activity: backpack, gear: book)
PackingList.create(activity: backpack, gear: gps)
PackingList.create(activity: backpack, gear: compass)
PackingList.create(activity: backpack, gear: traditional_backpack)
PackingList.create(activity: backpack, gear: lightweight_backpack)
PackingList.create(activity: backpack, gear: hammock)
PackingList.create(activity: backpack, gear: hiking_poles)
PackingList.create(activity: backpack, gear: first_aid_robust)
PackingList.create(activity: backpack, gear: cash)
PackingList.create(activity: backpack, gear: satellite_device)
PackingList.create(activity: backpack, gear: pcord)
PackingList.create(activity: backpack, gear: earplugs)
PackingList.create(activity: backpack, gear: trash_bag)
PackingList.create(activity: backpack, gear: usb_charger)
PackingList.create(activity: backpack, gear: phone_charger)
PackingList.create(activity: backpack, gear: snacks)
PackingList.create(activity: backpack, gear: breakfast)
PackingList.create(activity: backpack, gear: lunch)
PackingList.create(activity: backpack, gear: dinner)

# DAYHIKE LIST SEEDS
PackingList.create(activity: dayhike, gear: bladder)
PackingList.create(activity: dayhike, gear: knife)
PackingList.create(activity: dayhike, gear: headlamp)
PackingList.create(activity: dayhike, gear: batteries)
PackingList.create(activity: dayhike, gear: sunglasses)
PackingList.create(activity: dayhike, gear: sunscreen)
PackingList.create(activity: dayhike, gear: hat)
PackingList.create(activity: dayhike, gear: beanie)
PackingList.create(activity: dayhike, gear: chapstick)
PackingList.create(activity: dayhike, gear: tp)
PackingList.create(activity: dayhike, gear: waterproof_jacket)
PackingList.create(activity: dayhike, gear: waterproof_pants)
PackingList.create(activity: dayhike, gear: down_jacket)
PackingList.create(activity: dayhike, gear: buff)
PackingList.create(activity: dayhike, gear: shorts)
PackingList.create(activity: dayhike, gear: tshirt)
PackingList.create(activity: dayhike, gear: long_sleeve)
PackingList.create(activity: dayhike, gear: fleece)
PackingList.create(activity: dayhike, gear: hiking_shoes)
PackingList.create(activity: dayhike, gear: gps)
PackingList.create(activity: dayhike, gear: compass)
PackingList.create(activity: dayhike, gear: daypack)
PackingList.create(activity: dayhike, gear: hiking_poles)
PackingList.create(activity: dayhike, gear: first_aid_mini)
PackingList.create(activity: dayhike, gear: cash)
PackingList.create(activity: dayhike, gear: snacks)

# BACKCOUNTRY SKI LIST SEEDS
PackingList.create(activity: backcountry_ski, gear: water)
PackingList.create(activity: backcountry_ski, gear: water_bottle)
PackingList.create(activity: backcountry_ski, gear: bladder)
PackingList.create(activity: backcountry_ski, gear: knife)
PackingList.create(activity: backcountry_ski, gear: headlamp)
PackingList.create(activity: backcountry_ski, gear: sunglasses)
PackingList.create(activity: backcountry_ski, gear: sunscreen)
PackingList.create(activity: backcountry_ski, gear: hat)
PackingList.create(activity: backcountry_ski, gear: beanie)
PackingList.create(activity: backcountry_ski, gear: chapstick)
PackingList.create(activity: backcountry_ski, gear: tp)
PackingList.create(activity: backcountry_ski, gear: waterproof_jacket)
PackingList.create(activity: backcountry_ski, gear: waterproof_pants)
PackingList.create(activity: backcountry_ski, gear: down_jacket)
PackingList.create(activity: backcountry_ski, gear: gloves)
PackingList.create(activity: backcountry_ski, gear: buff)
PackingList.create(activity: backcountry_ski, gear: long_underwear)
PackingList.create(activity: backcountry_ski, gear: tshirt)
PackingList.create(activity: backcountry_ski, gear: long_sleeve)
PackingList.create(activity: backcountry_ski, gear: fleece)
PackingList.create(activity: backcountry_ski, gear: gps)
PackingList.create(activity: backcountry_ski, gear: compass)
PackingList.create(activity: backcountry_ski, gear: daypack)
PackingList.create(activity: backcountry_ski, gear: first_aid_mini)
PackingList.create(activity: backcountry_ski, gear: snacks)
PackingList.create(activity: backcountry_ski, gear: breakfast)
PackingList.create(activity: backcountry_ski, gear: lunch)
PackingList.create(activity: backcountry_ski, gear: dinner)
PackingList.create(activity: backcountry_ski, gear: skis)
PackingList.create(activity: backcountry_ski, gear: ski_boots)
PackingList.create(activity: backcountry_ski, gear: skins)
PackingList.create(activity: backcountry_ski, gear: beacon)
PackingList.create(activity: backcountry_ski, gear: probe)
PackingList.create(activity: backcountry_ski, gear: shovel)
PackingList.create(activity: backcountry_ski, gear: ski_poles)

# SKI HUT TRIP LIST SEEDS
PackingList.create(activity: hut, gear: water)
PackingList.create(activity: hut, gear: water_bottle)
PackingList.create(activity: hut, gear: bladder)
PackingList.create(activity: hut, gear: knife)
PackingList.create(activity: hut, gear: headlamp)
PackingList.create(activity: hut, gear: batteries)
PackingList.create(activity: hut, gear: sunglasses)
PackingList.create(activity: hut, gear: sunscreen)
PackingList.create(activity: hut, gear: hat)
PackingList.create(activity: hut, gear: beanie)
PackingList.create(activity: hut, gear: toothbrush)
PackingList.create(activity: hut, gear: chapstick)
PackingList.create(activity: hut, gear: tp)
PackingList.create(activity: hut, gear: wipes)
PackingList.create(activity: hut, gear: waterproof_jacket)
PackingList.create(activity: hut, gear: waterproof_pants)
PackingList.create(activity: hut, gear: down_jacket)
PackingList.create(activity: hut, gear: down_pants)
PackingList.create(activity: hut, gear: gloves)
PackingList.create(activity: hut, gear: buff)
PackingList.create(activity: hut, gear: underwear)
PackingList.create(activity: hut, gear: socks)
PackingList.create(activity: hut, gear: long_underwear)
PackingList.create(activity: hut, gear: shorts)
PackingList.create(activity: hut, gear: tshirt)
PackingList.create(activity: hut, gear: long_sleeve)
PackingList.create(activity: hut, gear: fleece)
PackingList.create(activity: hut, gear: cotton_shirt)
PackingList.create(activity: hut, gear: sleeping_bag)
PackingList.create(activity: hut, gear: sleep_socks)
PackingList.create(activity: hut, gear: flipflops)
PackingList.create(activity: hut, gear: book)
PackingList.create(activity: hut, gear: gps)
PackingList.create(activity: hut, gear: compass)
PackingList.create(activity: hut, gear: lightweight_backpack)
PackingList.create(activity: hut, gear: first_aid_robust)
PackingList.create(activity: hut, gear: cash)
PackingList.create(activity: hut, gear: satellite_device)
PackingList.create(activity: hut, gear: pcord)
PackingList.create(activity: hut, gear: earplugs)
PackingList.create(activity: hut, gear: trash_bag)
PackingList.create(activity: hut, gear: usb_charger)
PackingList.create(activity: hut, gear: phone_charger)
PackingList.create(activity: hut, gear: snacks)
PackingList.create(activity: hut, gear: breakfast)
PackingList.create(activity: hut, gear: lunch)
PackingList.create(activity: hut, gear: dinner)
PackingList.create(activity: hut, gear: skis)
PackingList.create(activity: hut, gear: ski_boots)
PackingList.create(activity: hut, gear: skins)
PackingList.create(activity: hut, gear: beacon)
PackingList.create(activity: hut, gear: probe)
PackingList.create(activity: hut, gear: shovel)
PackingList.create(activity: hut, gear: ski_poles)

# YOGA PACKING LIST
PackingList.create(activity: yoga, gear: water_bottle)
PackingList.create(activity: yoga, gear: sunglasses)
PackingList.create(activity: yoga, gear: sunscreen)
PackingList.create(activity: yoga, gear: hat)
PackingList.create(activity: yoga, gear: waterproof_jacket)
PackingList.create(activity: yoga, gear: shorts)
PackingList.create(activity: yoga, gear: tshirt)
PackingList.create(activity: yoga, gear: long_sleeve)
PackingList.create(activity: yoga, gear: hiking_shoes)
PackingList.create(activity: yoga, gear: daypack)
PackingList.create(activity: yoga, gear: snacks)
PackingList.create(activity: yoga, gear: yoga_mat)

# CLIMBING PACK LIST
PackingList.create(activity: climbing, gear: water_bottle)
PackingList.create(activity: climbing, gear: sunglasses)
PackingList.create(activity: climbing, gear: sunscreen)
PackingList.create(activity: climbing, gear: hat)
PackingList.create(activity: climbing, gear: waterproof_jacket)
PackingList.create(activity: climbing, gear: down_jacket)
PackingList.create(activity: climbing, gear: shorts)
PackingList.create(activity: climbing, gear: pants)
PackingList.create(activity: climbing, gear: tshirt)
PackingList.create(activity: climbing, gear: long_sleeve)
PackingList.create(activity: climbing, gear: fleece)
PackingList.create(activity: climbing, gear: hiking_shoes)
PackingList.create(activity: climbing, gear: climbing_shoes)
PackingList.create(activity: climbing, gear: daypack)
PackingList.create(activity: climbing, gear: snacks)
PackingList.create(activity: climbing, gear: lunch)
PackingList.create(activity: climbing, gear: rope)
PackingList.create(activity: climbing, gear: harness)
PackingList.create(activity: climbing, gear: belay_device)
PackingList.create(activity: climbing, gear: belay_gloves)
PackingList.create(activity: climbing, gear: helmet_climbing)
PackingList.create(activity: climbing, gear: speaker)

# MOUNTAIN BIKE PACKING LIST
PackingList.create(activity: mtn_biking, gear: water_bottle)
PackingList.create(activity: mtn_biking, gear: sunglasses)
PackingList.create(activity: mtn_biking, gear: sunscreen)
PackingList.create(activity: mtn_biking, gear: hat)
PackingList.create(activity: mtn_biking, gear: waterproof_jacket)
PackingList.create(activity: mtn_biking, gear: down_jacket)
PackingList.create(activity: mtn_biking, gear: shorts)
PackingList.create(activity: mtn_biking, gear: chamois)
PackingList.create(activity: mtn_biking, gear: padding)
PackingList.create(activity: mtn_biking, gear: gopro)
PackingList.create(activity: mtn_biking, gear: tshirt)
PackingList.create(activity: mtn_biking, gear: long_sleeve)
PackingList.create(activity: mtn_biking, gear: fleece)
PackingList.create(activity: mtn_biking, gear: buff)
PackingList.create(activity: mtn_biking, gear: bike_shoes)
PackingList.create(activity: mtn_biking, gear: daypack)
PackingList.create(activity: mtn_biking, gear: snacks)
PackingList.create(activity: mtn_biking, gear: lunch)
PackingList.create(activity: mtn_biking, gear: rope)
PackingList.create(activity: mtn_biking, gear: harness)
PackingList.create(activity: mtn_biking, gear: belay_device)
PackingList.create(activity: mtn_biking, gear: belay_gloves)
PackingList.create(activity: mtn_biking, gear: helmet_bike)