# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Activity.destroy_all
Gear.destroy_all

dayhike = Activity.create(name: "Dayhike", description: "Going for long walks, especially in the country or woods is callled hiking! A hike that is short enough to be completed in a single day", image: 'https://www.mountainphotography.com/images/large/201109_iceLakesAutumnHike.jpg')
backpack = Activity.create(name: "Backpack", description: "Backpacking is an adventure that blends hiking with backcountry camping. It lets you broaden your horizons beyond the car campground to enjoy a richer, more immersive outdoor experience. A key distinction from day hiking is the size of your pack—your backpack (and you) must carry all of life’s essentials on your back. And you must choose those essentials with care.", image: 'https://www.rei.com/dam/vagnini_101317_4227_hero_lg.jpg')
backcountry_ski = Activity.create(name: "Backcountry Skiing", description: "Backcountry skiing is skiing in the backcountry on unmarked or unpatrolled areas, and skiers need to be prepared - ski patrol is not coming to help.", image: 'https://www.switchbacktravel.com/sites/default/files/articles%20/Backcountry%20skiing%20(m).jpg')
climbing = Activity.create(name: "Rock Climbing", description: "Rock climbing can be performed on an indoor rock climbing wall or out in nature. With the right mindset and the best climbing equipment, shoes and gear for safe rock climbing, you can be prepared for unparelleled adventure!", image: 'https://climbinggeargeek.com/wp-content/uploads/2018/03/climbing_pack-766x500.png')
yoga = Activity.create(name: "Mountain Yoga", description: "Embrace the Experience. Being outside can intensify the yoga experience in many ways, since nature inspires all the things you try to drive home with students—focusing awareness, breathing deeply, practicing stillness.", image: 'https://i.pinimg.com/originals/09/08/65/09086577e20fbc0e6906a692d55a28e1.png')
mtn_biking = Activity.create(name: "Mountain Biking", description: "Mountain biking is a sport of riding bicycles off-road, often over rough terrain, using specially designed mountain bikes. Mountain bikes share similarities with other bikes but incorporate features designed to enhance durability and performance in rough terrain.", image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPOfttO5niLbU1aFzaRcxG2ROxhHAg8erhOw&usqp=CAU')
hut = Activity.create(name: "Winter Hut Trip", description: "Immerse yourself in the backcountry with the quickest access to breathtaking lines. Hole up in a hut for a few nights with good company and create memories that will last a lifetime!", image: 'https://cdn.allsummitcounty.com/images/content/5827_7088_Breckenridge_Colorado_Hut_Ski_Trip_lg.jpg')

water = Gear.create(name: "Water Filtration System", desciption: "", category: "Essential", image: "https://images.squarespace-cdn.com/content/v1/5346a846e4b0101b157468cf/1518269300014-HZRVS3XSC984E8XK7MJC/ke17ZwdGBToddI8pDm48kG87Sfbgg29A4BYEDq3OXvgUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcf4OxbJOyh_wHUnyc4kQLQ6SBshRGOku7c30Y_IRDNPta8R2IY5BHMaEj1zOWoDTZ/Top-down+view+of+the+best+backpacking+water+filters+on+the+market+laid+out+on+a+table+for+size+comparison?format=750w", link: "", weight: "2.0")
fire = Gear.create(name: "Fire Starter (matches or lighter)", desciption: "", category: "Essential",image: "https://cdn.coolofthewild.com/wp-content/uploads/2018/03/DIY-firestarter-kit.jpg", link: "", weight: "0.89")
stove = Gear.create(name: "Stove and Fuel", desciption: "", category: "Essential",image: "https://www.rei.com/dam/c01_5252_how_to_choose_backpacking_stoves_lg.jpg", link: "", weight: "10.9")
knife = Gear.create(name: "Knife", desciption: "", category: "Essential",image: "https://cdn.shopify.com/s/files/1/0880/2184/files/best-knives-and-multi-tools-for-hikers-and-backpackers-2_a9798339-ed7b-43ca-8ecf-034df05bd8aa.jpg?v=1502306674", link: "", weight: "0.0")
utensil = Gear.create(name: "Utensil", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
vessel = Gear.create(name: "Cup or Bowl", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
water_bottle = Gear.create(name: "Water Bottles", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
bladder = Gear.create(name: "Water Bladder", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
soap = Gear.create(name: "Biodegradable Soap", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
headlamp = Gear.create(name: "Headlamp",  desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
batteries = Gear.create(name: "Extra Batteries", desciption: "", category: "Essential",image: "", link: "", weight: "0.0")
sunglasses = Gear.create(name: "Sunglasses", desciption: "", category: "Outerwear", image: "", link: "", weight: "0.0")
suncreen = Gear.create(name: "Sunscreen", desciption: "", category: "Essential", image: "", link: "", weight: "0.0")
hat = Gear.create(name: "Sun Hat", desciption: "", category: "Outerwear", image: "", link: "", weight: "0.0")
beanie = Gear.create(name: "Winter Hat", desciption: "", category: "Outerwear", image: "", link: "", weight: "0.0")
toothbrush = Gear.create(name: "Toothbrush / paste", desciption: "", category: "Toiletries", image: "", link: "", weight: "0.0")
chapstick = Gear.create(name: "Chapstick", desciption: "", category: "Toiletries", image: "", link: "", weight: "0.0")
tp = Gear.create(name: "Toilet Paper and Hand Sanitizer", desciption: "", category: "Toiletries", image: "", link: "", weight: "0.0")
wag_bag = Gear.create(name: "Wag Bag", desciption: "", category: "Toiletries", image: "", link: "", weight: "0.0")
wipes = Gear.create(name: "Wet Wipes or Face Wipes",  desciption: "", category: "Toiletries", image: "", link: "", weight: "0.0")
waterproof_jacket = Gear.create(name: "Waterproof Jacket", desciption: "", category: "Outerwear", image: "", link: "", weight: "0.0")
waterproof_pants = Gear.create(name: "Waterproof Pants",  desciption: "", category: "Outerwear",image: "", link: "", weight: "0.0")
down_jacket = Gear.create(name: "Insulating Down Jacket",  desciption: "", category: "Outerwear",image: "", link: "", weight: "0.0")
down_pants = Gear.create(name: "Insulated Pants", desciption: "", category: "Outerwear", image: "", link: "", weight: "0.0")
gloves = Gear.create(name: "Gloves", image: "",  desciption: "", category: "Outerwear",link: "", weight: "0.0")
buff = Gear.create(name: "Bandana or Buff",  desciption: "", category: "Outerwear",image: "", link: "", weight: "0.0")
underwear = Gear.create(name: "Underwear", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
socks = Gear.create(name: "Socks", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
long_underwear = Gear.create(name: "Long Underwear / Baselayers", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
shorts = Gear.create(name: "Shorts", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
tshirt = Gear.create(name: "Wool T-shirt", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
long_sleeve = Gear.create(name: "Long-sleeve Shirt", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
fleece = Gear.create(name: "Fleece Mid Layer", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
cotton_shirt = Gear.create(name: "Cotton Sleep Shirt", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
sleeping_bag = Gear.create(name: "Sleeping Bag", desciption: "", category: "Essential", image: "", link: "", weight: "0.0")
sleeping_pad = Gear.create(name: "Sleeping Pad", desciption: "", category: "Essential", image: "", link: "", weight: "0.0")
sleep_socks = Gear.create(name: "Sleep Socks (keep them dry!)", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
tent = Gear.create(name: "Tent",  desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
flipflops = Gear.create(name: "Flipflops", desciption: "", category: "Footwear", image: "", link: "", weight: "0.0")
hiking_shoes = Gear.create(name: "Hiking Shoes", desciption: "", category: "Footwear", image: "", link: "", weight: "0.0")
climbing_shoes = Gear.create(name: "Climbing Shoes", desciption: "", category: "Footwear", image: "", link: "", weight: "0.0")
rope = Gear.create(name: "Climbing Rope", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
harness = Gear.create(name: "Harness", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
belay_device = Gear.create(name: "Belay Device", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
belay_gloves = Gear.create(name: "Belay Gloves", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
helmet_climbing = Gear.create(name: "Climbing Helmet", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
helmet_bike = Gear.create(name: "Mountain Biking Helmet", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
bike_shoes = Gear.create(name: "Mountain Bike Shoes", desciption: "", category: "Footwear", image: "", link: "", weight: "0.0")
chamois = Gear.create(name: "Bike Chamois", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
padding = Gear.create(name: "Elbow and Knee Pads", desciption: "", category: "Clothing", image: "", link: "", weight: "0.0")
book = Gear.create(name: "Book or Journal", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
gps = Gear.create(name: "Maps or GPS and/on phone", desciption: "", category: "Essential", image: "", link: "", weight: "0.0")
compass = Gear.create(name: "Compass", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
daypack = Gear.create(name: "Day Pack", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
traditional_backpack = Gear.create(name: "Backpack", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
lightweight_backpack = Gear.create(name: "Lightweight Backpack", desciption: "", category: "Gear", image: "", link: "", weight: "1.5")
hammock = Gear.create(name: "Hammock", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
speaker = Gear.create(name: "Bluetooth Speaker", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
hiking_poles = Gear.create(name: "Hiking Poles", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
first_aid_mini = Gear.create(name: "Mini First Aid Kit", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
first_aid_robust = Gear.create(name: "Robust First Aid Kit", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
cash = Gear.create(name: "Emergency Cash", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
satellite_device = Gear.create(name: "Spot or InReach", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
pcord = Gear.create(name: "Parachute Cord", desciption: "", category: "Emergency Gear", image: "", link: "", weight: "0.0")
skis = Gear.create(name: "AT Skis", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
ski_boots = Gear.create(name: "Ski Boots", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
skins = Gear.create(name: "Skins", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
beacon = Gear.create(name: "Beacon", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
probe = Gear.create(name: "Probe", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
shovel = Gear.create(name: "Shovel", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
ski_poles = Gear.create(name: "Ski Poles", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")
earplugs = Gear.create(name: "Earplugs", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
trash_bag = Gear.create(name: "Extra Trash Bag", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
usb_charger = Gear.create(name: "Portable USB Charger", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
phone_charger = Gear.create(name: "Phone Charger", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
gopro = Gear.create(name: "GoPro", desciption: "", category: "Optional", image: "", link: "", weight: "0.0")
snacks = Gear.create(name: "Snacks", desciption: "", category: "Food", image: "", link: "", weight: "0.0")
breakfast = Gear.create(name: "Breakfasts", desciption: "", category: "Food", image: "", link: "", weight: "0.0")
lunch = Gear.create(name: "Lunches", desciption: "", category: "Food", image: "", link: "", weight: "0.0")
dinner = Gear.create(name: "Dinner", desciption: "", category: "Food", image: "", link: "", weight: "0.0")
yoga_mat = Gear.create(name: "Yoga Mat", desciption: "", category: "Gear", image: "", link: "", weight: "0.0")


# BACKPACK LIST SEEDS
Packing_List.create(activity: backpack, gear: water)
Packing_List.create(activity: backpack, gear: water_bottle)
Packing_List.create(activity: backpack, gear: bladder)
Packing_List.create(activity: backpack, gear: fire)
Packing_List.create(activity: backpack, gear: stove)
Packing_List.create(activity: backpack, gear: knife)
Packing_List.create(activity: backpack, gear: utensil)
Packing_List.create(activity: backpack, gear: vessel)
Packing_List.create(activity: backpack, gear: soap)
Packing_List.create(activity: backpack, gear: headlamp)
Packing_List.create(activity: backpack, gear: batteries)
Packing_List.create(activity: backpack, gear: sunglasses)
Packing_List.create(activity: backpack, gear: sunscreen)
Packing_List.create(activity: backpack, gear: hat)
Packing_List.create(activity: backpack, gear: beanie)
Packing_List.create(activity: backpack, gear: toothbrush)
Packing_List.create(activity: backpack, gear: chapstick)
Packing_List.create(activity: backpack, gear: tp)
Packing_List.create(activity: backpack, gear: wipes)
Packing_List.create(activity: backpack, gear: waterproof_jacket)
Packing_List.create(activity: backpack, gear: waterproof_pants)
Packing_List.create(activity: backpack, gear: down_jacket)
Packing_List.create(activity: backpack, gear: down_pants)
Packing_List.create(activity: backpack, gear: gloves)
Packing_List.create(activity: backpack, gear: buff)
Packing_List.create(activity: backpack, gear: underwear)
Packing_List.create(activity: backpack, gear: socks)
Packing_List.create(activity: backpack, gear: long_underwear)
Packing_List.create(activity: backpack, gear: shorts)
Packing_List.create(activity: backpack, gear: tshirt)
Packing_List.create(activity: backpack, gear: long_sleeve)
Packing_List.create(activity: backpack, gear: fleece)
Packing_List.create(activity: backpack, gear: cotton_shirt)
Packing_List.create(activity: backpack, gear: sleeping_bag)
Packing_List.create(activity: backpack, gear: sleeping_pad)
Packing_List.create(activity: backpack, gear: sleep_socks)
Packing_List.create(activity: backpack, gear: tent)
Packing_List.create(activity: backpack, gear: flipflops)
Packing_List.create(activity: backpack, gear: hiking_shoes)
Packing_List.create(activity: backpack, gear: book)
Packing_List.create(activity: backpack, gear: gps)
Packing_List.create(activity: backpack, gear: compass)
Packing_List.create(activity: backpack, gear: traditional_backpack)
Packing_List.create(activity: backpack, gear: lightweight_backpack)
Packing_List.create(activity: backpack, gear: hammock)
Packing_List.create(activity: backpack, gear: hiking_poles)
Packing_List.create(activity: backpack, gear: first_aid_robust)
Packing_List.create(activity: backpack, gear: cash)
Packing_List.create(activity: backpack, gear: satellite_device)
Packing_List.create(activity: backpack, gear: pcord)
Packing_List.create(activity: backpack, gear: earplugs)
Packing_List.create(activity: backpack, gear: trash_bag)
Packing_List.create(activity: backpack, gear: usb_charger)
Packing_List.create(activity: backpack, gear: phone_charger)
Packing_List.create(activity: backpack, gear: snacks)
Packing_List.create(activity: backpack, gear: breakfast)
Packing_List.create(activity: backpack, gear: lunch)
Packing_List.create(activity: backpack, gear: dinner)

# DAYHIKE LIST SEEDS
Packing_List.create(activity: dayhike, gear: bladder)
Packing_List.create(activity: dayhike, gear: knife)
Packing_List.create(activity: dayhike, gear: headlamp)
Packing_List.create(activity: dayhike, gear: batteries)
Packing_List.create(activity: dayhike, gear: sunglasses)
Packing_List.create(activity: dayhike, gear: sunscreen)
Packing_List.create(activity: dayhike, gear: hat)
Packing_List.create(activity: dayhike, gear: beanie)
Packing_List.create(activity: dayhike, gear: chapstick)
Packing_List.create(activity: dayhike, gear: tp)
Packing_List.create(activity: dayhike, gear: waterproof_jacket)
Packing_List.create(activity: dayhike, gear: waterproof_pants)
Packing_List.create(activity: dayhike, gear: down_jacket)
Packing_List.create(activity: dayhike, gear: buff)
Packing_List.create(activity: dayhike, gear: shorts)
Packing_List.create(activity: dayhike, gear: tshirt)
Packing_List.create(activity: dayhike, gear: long_sleeve)
Packing_List.create(activity: dayhike, gear: fleece)
Packing_List.create(activity: dayhike, gear: hiking_shoes)
Packing_List.create(activity: dayhike, gear: gps)
Packing_List.create(activity: dayhike, gear: compass)
Packing_List.create(activity: dayhike, gear: daypack)
Packing_List.create(activity: dayhike, gear: hiking_poles)
Packing_List.create(activity: dayhike, gear: first_aid_mini)
Packing_List.create(activity: dayhike, gear: cash)
Packing_List.create(activity: dayhike, gear: snacks)

# SKI HUT TRIP LIST SEEDS
Packing_List.create(activity: hut, gear: water)
Packing_List.create(activity: hut, gear: water_bottle)
Packing_List.create(activity: hut, gear: bladder)
Packing_List.create(activity: hut, gear: knife)
Packing_List.create(activity: hut, gear: headlamp)
Packing_List.create(activity: hut, gear: batteries)
Packing_List.create(activity: hut, gear: sunglasses)
Packing_List.create(activity: hut, gear: sunscreen)
Packing_List.create(activity: hut, gear: hat)
Packing_List.create(activity: hut, gear: beanie)
Packing_List.create(activity: hut, gear: toothbrush)
Packing_List.create(activity: hut, gear: chapstick)
Packing_List.create(activity: hut, gear: tp)
Packing_List.create(activity: hut, gear: wipes)
Packing_List.create(activity: hut, gear: waterproof_jacket)
Packing_List.create(activity: hut, gear: waterproof_pants)
Packing_List.create(activity: hut, gear: down_jacket)
Packing_List.create(activity: hut, gear: down_pants)
Packing_List.create(activity: hut, gear: gloves)
Packing_List.create(activity: hut, gear: buff)
Packing_List.create(activity: hut, gear: underwear)
Packing_List.create(activity: hut, gear: socks)
Packing_List.create(activity: hut, gear: long_underwear)
Packing_List.create(activity: hut, gear: shorts)
Packing_List.create(activity: hut, gear: tshirt)
Packing_List.create(activity: hut, gear: long_sleeve)
Packing_List.create(activity: hut, gear: fleece)
Packing_List.create(activity: hut, gear: cotton_shirt)
Packing_List.create(activity: hut, gear: sleeping_bag)
Packing_List.create(activity: hut, gear: sleep_socks)
Packing_List.create(activity: hut, gear: flipflops)
Packing_List.create(activity: hut, gear: book)
Packing_List.create(activity: hut, gear: gps)
Packing_List.create(activity: hut, gear: compass)
Packing_List.create(activity: hut, gear: lightweight_backpack)
Packing_List.create(activity: hut, gear: first_aid_robust)
Packing_List.create(activity: hut, gear: cash)
Packing_List.create(activity: hut, gear: satellite_device)
Packing_List.create(activity: hut, gear: pcord)
Packing_List.create(activity: hut, gear: earplugs)
Packing_List.create(activity: hut, gear: trash_bag)
Packing_List.create(activity: hut, gear: usb_charger)
Packing_List.create(activity: hut, gear: phone_charger)
Packing_List.create(activity: hut, gear: snacks)
Packing_List.create(activity: hut, gear: breakfast)
Packing_List.create(activity: hut, gear: lunch)
Packing_List.create(activity: hut, gear: dinner)
Packing_List.create(activity: hut, gear: skis)
Packing_List.create(activity: hut, gear: ski_boots)
Packing_List.create(activity: hut, gear: skins)
Packing_List.create(activity: hut, gear: beacon)
Packing_List.create(activity: hut, gear: probe)
Packing_List.create(activity: hut, gear: shovel)
Packing_List.create(activity: hut, gear: ski_poles)

# YOGA PACKING LIST
Packing_List.create(activity: dayhike, gear: water_bottle)
Packing_List.create(activity: dayhike, gear: sunglasses)
Packing_List.create(activity: dayhike, gear: sunscreen)
Packing_List.create(activity: dayhike, gear: hat)
Packing_List.create(activity: dayhike, gear: waterproof_jacket)
Packing_List.create(activity: dayhike, gear: down_jacket)
Packing_List.create(activity: dayhike, gear: shorts)
Packing_List.create(activity: dayhike, gear: tshirt)
Packing_List.create(activity: dayhike, gear: long_sleeve)
Packing_List.create(activity: dayhike, gear: fleece)
Packing_List.create(activity: dayhike, gear: hiking_shoes)
Packing_List.create(activity: dayhike, gear: daypack)
Packing_List.create(activity: dayhike, gear: snacks)
Packing_List.create(activity: dayhike, gear: yoga_mat)

# CLIMBING PACK LIST
Packing_List.create(activity: climbing, gear: water_bottle)
Packing_List.create(activity: climbing, gear: sunglasses)
Packing_List.create(activity: climbing, gear: sunscreen)
Packing_List.create(activity: climbing, gear: hat)
Packing_List.create(activity: climbing, gear: waterproof_jacket)
Packing_List.create(activity: climbing, gear: down_jacket)
Packing_List.create(activity: climbing, gear: shorts)
Packing_List.create(activity: climbing, gear: tshirt)
Packing_List.create(activity: climbing, gear: long_sleeve)
Packing_List.create(activity: climbing, gear: fleece)
Packing_List.create(activity: climbing, gear: hiking_shoes)
Packing_List.create(activity: climbing, gear: climbing_shoes)
Packing_List.create(activity: climbing, gear: daypack)
Packing_List.create(activity: climbing, gear: snacks)
Packing_List.create(activity: climbing, gear: lunch)
Packing_List.create(activity: climbing, gear: rope)
Packing_List.create(activity: climbing, gear: harness)
Packing_List.create(activity: climbing, gear: belay_device)
Packing_List.create(activity: climbing, gear: belay_gloves)
Packing_List.create(activity: climbing, gear: helmet_climbing)
Packing_List.create(activity: climbing, gear: speaker)

# YOGA PACKING LIST
Packing_List.create(activity: mtn_biking, gear: water_bottle)
Packing_List.create(activity: mtn_biking, gear: sunglasses)
Packing_List.create(activity: mtn_biking, gear: sunscreen)
Packing_List.create(activity: mtn_biking, gear: hat)
Packing_List.create(activity: mtn_biking, gear: waterproof_jacket)
Packing_List.create(activity: mtn_biking, gear: down_jacket)
Packing_List.create(activity: mtn_biking, gear: shorts)
Packing_List.create(activity: mtn_biking, gear: chamois)
Packing_List.create(activity: mtn_biking, gear: padding)
Packing_List.create(activity: mtn_biking, gear: gopro)
Packing_List.create(activity: mtn_biking, gear: tshirt)
Packing_List.create(activity: mtn_biking, gear: long_sleeve)
Packing_List.create(activity: mtn_biking, gear: fleece)
Packing_List.create(activity: mtn_biking, gear: buff)
Packing_List.create(activity: mtn_biking, gear: bike_shoes)
Packing_List.create(activity: mtn_biking, gear: daypack)
Packing_List.create(activity: mtn_biking, gear: snacks)
Packing_List.create(activity: mtn_biking, gear: lunch)
Packing_List.create(activity: mtn_biking, gear: rope)
Packing_List.create(activity: mtn_biking, gear: harness)
Packing_List.create(activity: mtn_biking, gear: belay_device)
Packing_List.create(activity: mtn_biking, gear: belay_gloves)
Packing_List.create(activity: mtn_biking, gear: helmet_bike)


